FROM php:8.4-cli

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    ca-certificates \
    libpq-dev \
    libzip-dev \
    libgd-dev \
    && docker-php-ext-install pdo_pgsql pgsql zip gd \
    && rm -rf /var/lib/apt/lists/*

RUN printf '%s\n' \
    'upload_max_filesize=12M' \
    'post_max_size=60M' \
    'max_file_uploads=10' \
    'max_execution_time=120' \
    'max_input_time=120' \
    'memory_limit=256M' \
    > /usr/local/etc/php/conf.d/uploads.ini

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY . .

RUN composer install \
    --no-dev \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader

RUN chmod -R 775 storage bootstrap/cache

EXPOSE 10000

CMD ["sh", "-c", "php artisan config:clear && php artisan cache:clear && php artisan route:clear && php artisan view:clear && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=10000"]
